config/routes.rb
Statusly::Application.routes.draw do
  root to: "application#index"
  resources :users
  resources :statuses, only: [:create, :show]
  resources :feed_items, only: [:index]
  resources :pending_requests, only: [:create]

  post "login" => "sessions#create", as: "login"
  get "logout" => "sessions#destroy", as: "logout"
  post "accept_request" => "feed_sources#create", as: "accept_request"
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  has_many :feed_sources
end

app/models/feed_source.rb
class FeedSource < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user

  attr_accessible :user
end

app/models/pending_request.rb
class PendingRequest < ActiveRecord::Base

  belongs_to :requestor, class_name: 'User'
  belongs_to :user

  attr_accessible :requestor
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user

  attr_accessible :text
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password

  has_many :statuses, order: 'created_at DESC'
  has_one :feed
  has_many :feed_sources, through: :feed
  has_many :pending_requests

  def self.create_with_password(username, password, password_confirmation)
    User.create do |user|
      user.username = username
      user.password = password
      user.password_confirmation = password_confirmation
    end
  end

  def add_feed_source(user_to_follow)
    create_feed unless feed
    feed.feed_sources.create(user: user_to_follow)
  end

  def feed_items(after = nil)
    feed_items = []
    feed.feed_sources.each do |source|
      if after
        after = Time.parse(after.to_s)+1
        feed_items << source.user.statuses.where("created_at > ?", after)
      else
        feed_items << source.user.statuses
      end
    end
    feed_items.flatten!
    feed_items.sort_by {|item| item.created_at}.reverse
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def index
    if logged_in?
      @status = Status.new
      render "index"
    else
      @user = User.new
      render "login"
    end
  end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  respond_to :json

  before_filter :require_login

  def index
    @feed_items = current_user.feed_items(params[:after])
    respond_with @feed_items
  end

end

app/controllers/feed_sources_controller.rb
class FeedSourcesController < ApplicationController
  before_filter :require_login
  def create

    request = current_user.pending_requests.find_by_requestor_id(params[:user])
    source = request.requestor.add_feed_source(current_user)
    if source
      request.destroy
    end
    redirect_to root_path
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :require_login

  def create

    user_to_follow = User.find_by_id(params[:user])
    if user_to_follow
      current_user.add_feed_source(user_to_follow)
    else
      flash[:error] = "You can't follow that person"
    end
    redirect_to current_user

  end

end

app/controllers/pending_requests_controller.rb
class PendingRequestsController < ApplicationController

  before_filter :require_login

  def create
    user_to_follow = User.find_by_id(params[:user])
    if user_to_follow
      request = user_to_follow.pending_requests.create(requestor: current_user)
    else
      flash[:error] = "You can't follow that person"
    end
    redirect_to current_user

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = login(params[:username], params[:password])
    if @user
      redirect_to root_path
    else
      redirect_back_or_to root_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  respond_to :json

  before_filter :require_login, only: [:create]

  def create
    @status = current_user.statuses.create(params[:status])
    respond_with @status, root: false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    attributes = params[:user]
    user = User.create_with_password(attributes[:username],attributes[:password], attributes[:password_confirmation])
    if user
      auto_login(user)
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_login.html.haml
%h1 Statusly
%h2 Register
= form_for @user do |f|
  .fieldset
    = f.label :username
    = f.text_field :username
  .fieldset
    = f.label :password
    = f.password_field :password
  .fieldset
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .fieldset
    = f.submit
%h2 Login
= form_tag login_path do
  .fieldset
    = label_tag :username
    = text_field_tag :username
  .fieldset
    = label_tag  :password
    = password_field_tag  :password
  .fieldset
    = submit_tag

app/views/application/index.html.haml
%h1 #{current_user.username}'s Page

%h2 Pending Friend Requests

- if current_user.pending_requests.empty?
  You have no pending requests
-else
  %ul
    - current_user.pending_requests.each do |request|
      %li
        =request.requestor.username
        =button_to "Accept Request", accept_request_path(user: request.requestor)


%h2 Your Statuses
= form_for @status, remote: true do |f|
  = f.text_area :text
  = f.submit

%ul#statuses
  - current_user.statuses.each do |status|
    %li
      = status.text

%h2 Feed
- if current_user.feed
  - if current_user.feed_items.empty?
    Your feed is empty!
  - else
    %ul#feed
      - current_user.feed_items.each do |item|
        %li{data:{timestamp: "#{item.created_at}"}} #{item.user.username}: #{item.text}
-else
  You don't have a feed!

= content_for :extra_scripts do
  = javascript_include_tag "post_status"
  = javascript_include_tag "update_feed"

app/views/application/login.html.haml
%h1 Statusly
%h2 Register
= form_for @user do |f|
  .fieldset
    = f.label :username
    = f.text_field :username
  .fieldset
    = f.label :password
    = f.password_field :password
  .fieldset
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .fieldset
    = f.submit
%h2 Login
= form_tag login_path do
  .fieldset
    = label_tag :username
    = text_field_tag :username
  .fieldset
    = label_tag  :password
    = password_field_tag  :password
  .fieldset
    = submit_tag

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Statusly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <%= link_to "logout of #{current_user.username}", logout_path %>
<% end %>
<%= yield %>

<%= yield :extra_scripts%>

</body>
</html>

app/views/users/show.html.haml
%h1 #{@user.username}'s Page

- if @user != current_user
  = button_to('follow', action: :create, controller: 'pending_requests', user: @user)
- else
  This is your profile page.
  = link_to "Go to your feed.", root_path